export const parks = [
    {
        park: 'Acadia',
        location: 'Maine',
        lat: 44.35,
        lng: -68.21,
    },
    {
        park: 'American Samoa',
        location: 'American Samoa',
        lat: -14.25,
        lng: -170.68,
    },
    {
        park: 'Arches',
        location: 'Utah',
        lat: 38.68,
        lng: -109.57,
    },
    {
        park: 'Badlands',
        location: 'South Dakota',
        lat: 43.75,
        lng: -102.5,
    },
    {
        park: 'Big Bend',
        location: 'Texas',
        lat: 29.25,
        lng: -103.25,
    },
    {
        park: 'Biscayne',
        location: 'Florida',
        lat: 25.65,
        lng: -80.08,
    },
    {
        park: 'Black Canyon of the Gunnison',
        location: 'Colorado',
        lat: 38.57,
        lng: -107.72,
    },
    {
        park: 'Bryce Canyon',
        location: 'Utah',
        lat: 37.57,
        lng: -112.18,
    },
    {
        park: 'Canyonlands',
        location: 'Utah',
        lat: 38.2,
        lng: -109.93,
    },
    {
        park: 'Capitol Reef',
        location: 'Utah',
        lat: 38.2,
        lng: -111.17,
    },
    {
        park: 'Carlsbad Caverns',
        location: 'New Mexico',
        lat: 32.17,
        lng: -104.44,
    },
    {
        park: 'Channel Islands',
        location: 'California',
        lat: 34.01,
        lng: -119.42,
    },
    {
        park: 'Congaree',
        location: 'South Carolina',
        lat: 33.78,
        lng: -80.78,
    },
    {
        park: 'Crater Lake',
        location: 'Oregon',
        lat: 42.94,
        lng: -122.1,
    },
    {
        park: 'Cuyahoga Valley',
        location: 'Ohio',
        lat: 41.24,
        lng: -81.55,
    },
    {
        park: 'Death Valley',
        location: 'California, Nevada',
        lat: 36.24,
        lng: -116.82,
    },
    {
        park: 'Denali',
        location: 'Alaska',
        lat: 63.33,
        lng: -150.5,
    },
    {
        park: 'Dry Tortugas',
        location: 'Florida',
        lat: 24.63,
        lng: -82.87,
    },
    {
        park: 'Everglades',
        location: 'Florida',
        lat: 25.32,
        lng: -80.93,
    },
    {
        park: 'Gates of the Arctic',
        location: 'Alaska',
        lat: 67.78,
        lng: -153.3,
    },
    {
        park: 'Gateway Arch',
        location: 'Missouri',
        lat: 38.63,
        lng: -90.19,
    },
    {
        park: 'Glacier',
        location: 'Montana',
        lat: 48.8,
        lng: -114,
    },
    {
        park: 'Glacier Bay',
        location: 'Alaska',
        lat: 58.5,
        lng: -137,
    },
    {
        park: 'Grand Canyon',
        location: 'Arizona',
        lat: 36.06,
        lng: -112.14,
    },
    {
        park: 'Grand Teton',
        location: 'Wyoming',
        lat: 43.73,
        lng: -110.8,
    },
    {
        park: 'Great Basin',
        location: 'Nevada',
        lat: 38.98,
        lng: -114.3,
    },
    {
        park: 'Great Sand Dunes',
        location: 'Colorado',
        lat: 37.73,
        lng: -105.51,
    },
    {
        park: 'Great Smoky Mountains',
        location: 'North Carolina, Tennessee',
        lat: 35.68,
        lng: -83.53,
    },
    {
        park: 'Guadalupe Mountains',
        location: 'Texas',
        lat: 31.92,
        lng: -104.87,
    },
    {
        park: 'Haleakalā',
        location: 'Hawaii',
        lat: 20.72,
        lng: -156.17,
    },
    {
        park: 'Hawaiʻi Volcanoes',
        location: 'Hawaii',
        lat: 19.38,
        lng: -155.2,
    },
    {
        park: 'Hot Springs',
        location: 'Arkansas',
        lat: 34.51,
        lng: -93.05,
    },
    {
        park: 'Indiana Dunes',
        location: 'Indiana',
        lat: 41.6533,
        lng: -87.0524,
    },
    {
        park: 'Isle Royale',
        location: 'Michigan',
        lat: 48.1,
        lng: -88.55,
    },
    {
        park: 'Joshua Tree',
        location: 'California',
        lat: 33.79,
        lng: -115.9,
    },
    {
        park: 'Katmai',
        location: 'Alaska',
        lat: 58.5,
        lng: -155,
    },
    {
        park: 'Kenai Fjords',
        location: 'Alaska',
        lat: 59.92,
        lng: -149.65,
    },
    {
        park: 'Kings Canyon',
        location: 'California',
        lat: 36.8,
        lng: -118.55,
    },
    {
        park: 'Kobuk Valley',
        location: 'Alaska',
        lat: 67.55,
        lng: -159.28,
    },
    {
        park: 'Lake Clark',
        location: 'Alaska',
        lat: 60.97,
        lng: -153.42,
    },
    {
        park: 'Lassen Volcanic',
        location: 'California',
        lat: 40.49,
        lng: -121.51,
    },
    {
        park: 'Mammoth Cave',
        location: 'Kentucky',
        lat: 37.18,
        lng: -86.1,
    },
    {
        park: 'Mesa Verde',
        location: 'Colorado',
        lat: 37.18,
        lng: -108.49,
    },
    {
        park: 'Mount Rainier',
        location: 'Washington',
        lat: 46.85,
        lng: -121.75,
    },
    {
        park: 'North Cascades',
        location: 'Washington',
        lat: 48.7,
        lng: -121.2,
    },
    {
        park: 'Olympic',
        location: 'Washington',
        lat: 47.97,
        lng: -123.5,
    },
    {
        park: 'Petrified Forest',
        location: 'Arizona',
        lat: 35.07,
        lng: -109.78,
    },
    {
        park: 'Pinnacles',
        location: 'California',
        lat: 36.48,
        lng: -121.16,
    },
    {
        park: 'Redwood',
        location: 'California',
        lat: 41.3,
        lng: -124,
    },
    {
        park: 'Rocky Mountain',
        location: 'Colorado',
        lat: 40.4,
        lng: -105.58,
    },
    {
        park: 'Saguaro',
        location: 'Arizona',
        lat: 32.25,
        lng: -110.5,
    },
    {
        park: 'Sequoia',
        location: 'California',
        lat: 36.43,
        lng: -118.68,
    },
    {
        park: 'Shenandoah',
        location: 'Virginia',
        lat: 38.53,
        lng: -78.35,
    },
    {
        park: 'Theodore Roosevelt',
        location: 'North Dakota',
        lat: 46.97,
        lng: -103.45,
    },
    {
        park: 'Virgin Islands',
        location: 'U.S. Virgin Islands',
        lat: 18.33,
        lng: -64.73,
    },
    {
        park: 'Voyageurs',
        location: 'Minnesota',
        lat: 48.5,
        lng: -92.88,
    },
    {
        park: 'White Sands',
        location: 'New Mexico',
        lat: 32.78,
        lng: -106.17,
    },
    {
        park: 'Wind Cave',
        location: 'South Dakota',
        lat: 43.57,
        lng: -103.48,
    },
    {
        park: 'Wrangell–St. Elias',
        location: 'Alaska',
        lat: 61,
        lng: -142,
    },
    {
        park: 'Yellowstone',
        location: 'Wyoming, Montana, Idaho',
        lat: 44.6,
        lng: -110.5,
    },
    {
        park: 'Yosemite',
        location: 'California',
        lat: 37.83,
        lng: -119.5,
    },
    {
        park: 'Zion',
        location: 'Utah',
        lat: 37.3,
        lng: -113.05,
    },
];
